### PR TITLE
Delete audio policy for deprecated `a2dp` module

### PR DESCRIPTION
**Pull request by MarijnS95**
The deprecated a2dp module is finally inaccessible on Android T, and has been [removed from common]: delete the `bluetooth_legacy_hal.xml` config here that would otherwise be pointing to the now-inexistant `a2dp_audio_policy_configuration.xml` file, and remove A2DP input (only applicable to sinks like infotainment systems) from `a2dp_in_audio_policy_configuration.xml` which is now unavailable in the same fashion.

[removed from common]: https://github.com/sonyxperiadev/device-sony-common/pull/899

### CODE REVIEW

**Comment by bartcubbins** [comment]
It's gone with today's audio configs update. @MarijnS95 I'm sorry, I only just noticed this PR

**Comment by MarijnS95** [comment]
@bartcubbins oh no #17 looks super messy, can we please invert the order of the patches and land this first?

**Comment by MarijnS95** [comment]
@bartcubbins you also landed that on the S branch but removal of the backwards-compat layer only applies to T :disappointed:

**Comment by MarijnS95** [comment]
@bartcubbins I've now reverted your PR as part of this one. Please split it up in multiple patches so that we can more clearly reason about the changes that are being made, rather than stomping right over other peoples work "because downstream says so".

This unfortunate approach to creating and merging patches is why I've pretty much abandoned SODP in favour of mainline, at least there _most_ developers and maintainers agree that that's _Not The Way™_.

**Comment by MarijnS95** [comment]
Blame is also partly on me for not vetting my own PRs, this patch got merged for every platform except Sagami and I forgot to check up on it :sweat_smile:

**Comment by bartcubbins** [comment]
I don't have time for this. revert my change and leave it as is.

**Comment by MarijnS95** [comment]
It's fine to keep config changes to big files, I would however like to be more careful with the policy configuration as we spent a lot of time to get it "just right" :)

**Comment by jerpelea** [comment]
@MarijnS95 thanks for spotting it. I removed the patch from s-mr1

**Comment by MarijnS95** [comment]
@jerpelea thanks! I didn't want to revert all of @bartcubbins' work so we should seek to re-land most bits and carefully adjust the policy to match.

**Pull request merged**
